# Generated by Django 2.0.6 on 2018-07-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_naturals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=200)),
                ('tvr', models.FloatField()),
                ('affinity', models.FloatField()),
                ('tcpp', models.FloatField()),
                ('mandatory_placement', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('C', 'Calculate')], max_length=10)),
                ('prime_time', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
