# Generated by Django 2.0.6 on 2018-07-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_naturals', '0002_auto_20180704_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='distr',
            field=models.CharField(default='National', max_length=50),
        ),
        migrations.AlterField(
            model_name='channels',
            name='mandatory_placement',
            field=models.CharField(max_length=10),
        ),
    ]
